### PR TITLE
Add `qem1` to the scan via GUI

### PR DESCRIPTION
**Pull request by mrakitin**
Tested the changes with Erik at the beamline.

### CODE REVIEW

**Comment by erikfarquhar** [comment]
I spent a while testing this under real-world conditions this evening. I found that the data seems to be written into the databroker entry *before* the intensity blip from the latest shutter actuation is seem in the qem1.ts.current1 data. I toyed with various delays within the xfp_plan_fast_shutter function: 

- increasing the wait time after the fast shutter fires (line 816: `yield from bps.sleep(exp_time*1.1)`) 
- introducing a delay in the count step (line 821: `return (yield from bp.count([qem1.ts, ht.x, ht.y], md=d))`)

Neither worked and they actually distorted the qem1.ts.current1 time-series data in a way that I don't understand. Adjusting the acquisition parameters (num points and averaging time) for the time-series didn't have any impact either.

The good news is that this doesn't seem to impact experiments, so just need to understand/fix the timing issue and then we can merge this feature into the master branch.

**Comment by erikfarquhar** [comment]
Closing for now, test/integrate on current version when opportunity permits.

**Comment by mrakitin** [comment]
This PR was closed without merging. @erikfarquhar, is it what you wanted?

**Comment by erikfarquhar** [comment]
@mrakitin yes, didn't feel like fighting with merge conflicts. It's been superseded by https://github.com/NSLS-II-XFP/profile_collection/pull/27. This new branch has a short sleep period to solve that issue I mentioned in an earlier comment about missing the blip. Haven't bothered to merge it in yet, might do so soon since I have some time to poke at this more.

**Pull request closed without merging**
